# Persistent volume

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
 name: phpmyadmin-deploy
spec:
 replicas: 1
 selector:
  matchLabels:
   app: phpmyadmin
 template:
  metadata:
   labels:
    app: phpmyadmin
  spec:
   containers:
   - name: phpmyadmin
     image: phpmyadmin:ysaito
     imagePullPolicy: Never
     ports:
     - containerPort: 5000

---
# service: Mediate access to pods.
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: phpmyadmin