# Persistent volume

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
 name: phpmyadmin-deploy
spec:
 replicas:	1
 selector:
  matchLabels:
   app: phpmyadmin
 template:
  metadata:
   labels:
    app: phpmyadmin
  spec:
   containers:
   - name: phpmyadmin
     image: phpmyadmin:ysaito
     imagePullPolicy: Never
     ports:
     - containerPort: 5000

---
# service: Mediate access to pods.
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.240
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: nginx