# Persistent volume

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
 name: ftps-deploy
spec:
 replicas:	1
 selector:
  matchLabels:
   app: ftps
 template:
  metadata:
   labels:
    app: ftps
  spec:
   containers:
   - name: ftps
     image: ftps:ysaito
     imagePullPolicy: Never
     ports:
     - containerPort: 21
    # - containerPort: 443
    #   name: https

---
# service: Mediate access to pods.
apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  #annotations:
  #  metallb.universe.tf/address-pool: default
  labels:
   app: ftps
spec:
  type: LoadBalancer
  #loadBalancerIP: 192.168.1.240
  ports:
  - port: 21
  selector:
    app: ftps