apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deploy
spec:
  replicas:	1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      volumes:
      - name: ftps-volume
        persistentVolumeClaim:
          claimName: ftps-pvc
      containers:
      - name: ftps
        image: ftps:ysaito
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 21000
        - containerPort: 21001
        - containerPort: 21002
        - containerPort: 21003
        - containerPort: 21004
        - containerPort: 21005
        - containerPort: 21006
        - containerPort: 21007
        - containerPort: 21008
        - containerPort: 21009
        volumeMounts:
        - name: ftps-volume
          mountPath: /home
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - 'pgrep telegraf && pgrep vsftpd'  
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 3
---

apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services
  labels:
    app: ftps
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.49.2
  ports:
  - name: ftp-data
    port: 20
    targetPort: 20
  - name: ftp-control
    port: 21
    targetPort: 21
  - name: pasv-21000
    port: 21000
    targetPort: 21000
  - name: pasv-21001
    port: 21001
    targetPort: 21001
  - name: pasv-21002
    port: 21002
    targetPort: 21002
  - name: pasv-21003
    port: 21003
    targetPort: 21003
  - name: pasv-21004
    port: 21004
    targetPort: 21004
  - name: pasv-21005
    port: 21005
    targetPort: 21005
  - name: pasv-21006
    port: 21006
    targetPort: 21006
  - name: pasv-21007
    port: 21007
    targetPort: 21007
  - name: pasv-21008
    port: 21008
    targetPort: 21008
  - name: pasv-21009
    port: 21009
    targetPort: 21009
  selector:
    app: ftps