# Persistent volume

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
 name: grafana-deploy
spec:
 replicas:	1
 selector:
  matchLabels:
   app: grafana
 template:
  metadata:
   name: grafana-pod
   labels:
    app: grafana
  spec:
   containers:
   - name: grafana
     image: grafana:ysaito
     imagePullPolicy: Never
     ports:
     - containerPort: 3000
---
# service: Mediate access to pods.
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  annotations:
   metallb.universe.tf/allow-shared-ip: ft_services
  labels:
   app: grafana
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.50.3
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: grafana