apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deploy
spec:
  replicas:	1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana-pod
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana:ysaito
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: grafana-creds
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/setup.sh
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 3
---

apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  annotations:
   metallb.universe.tf/allow-shared-ip: ft_services
  labels:
   app: grafana
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.49.2
  ports:
  - name: grafana
    port: 3000
    targetPort: 3000
  selector:
    app: grafana