apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
spec:
  replicas:	1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql
  spec:
    volumes:
    - name: mysql-pvc
      persistentVolumeClaim:
        claimName: ft-services-pvc
    containers:
    - name: mysql
      image: mysql:ysaito
      imagePullPolicy: Never
      ports:
      - containerPort: 3306
      volumeMounts:
      - name: mysql-pvc
        mountPath: /var/lib/mysql
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
