# Persistent volume

apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deploy
spec:
 replicas:	1
 selector:
  matchLabels:
   app: nginx
 template:
  metadata:
   name: nginx-pod
   labels:
    app: nginx
  spec:
   containers:
   - name: nginx
     image: nginx:ysaito
     imagePullPolicy: Never
     ports:
     - containerPort: 80
       name: http
     - containerPort: 443
       name: https
     - containerPort: 22
       name: ssh
---
# service: Mediate access to pods.
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  annotations:
   metallb.universe.tf/allow-shared-ip: ft_services
  labels:
   app: nginx
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.11.11
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  - name: ssh
    port: 22
    targetPort: 22
  selector:
    app: nginx