apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      name: phpmyadmin-pod
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:ysaito
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - 'pgrep telegraf && pgrep nginx && pgrep php-fpm'
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 3
---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 5000
    targetPort: 5000
  selector:
    app: phpmyadmin