# Persistent volume

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
 name: phpmyadmin-deploy
spec:
 replicas: 1
 selector:
  matchLabels:
   app: phpmyadmin
 template:
  metadata:
   name: phpmyadmin-pod
   labels:
    app: phpmyadmin
  spec:
   containers:
   - name: phpmyadmin
     image: phpmyadmin:ysaito
     imagePullPolicy: Never
     ports:
     - containerPort: 5000

---
# service: Mediate access to pods.
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_svcs
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.0.3
  ports:
  - name: phpmyadmin
    port: 5000
    targetPort: 5000
  selector:
    app: phpmyadmin