apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
spec:
  replicas:	1
  selector:
    matchLabels:
      app: wordrpess
  template:
    metadata:
      name: wordpress-pod
      labels:
        app: wordrpess
    spec:
      containers:
      - name: wordpress
        image: wordpress:ysaito
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/setup.sh
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 3
---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  annotations:
   metallb.universe.tf/allow-shared-ip: ft_services
  labels:
   app: wordpress
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.49.2
  ports:
  - name: wordpress
    port: 5050
    targetPort: 5050
  selector:
    app: wordrpess