# Persistent volume

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
 name: wordpress-deploy
spec:
 replicas:	1
 selector:
  matchLabels:
   app: wordrpess
 template:
  metadata:
   name: wordpress-pod
   labels:
    app: wordrpess
  spec:
   containers:
   - name: wordpress
     image: wordpress:ysaito
     imagePullPolicy: Never
     ports:
     - containerPort: 5050
---
# service: Mediate access to pods.
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  annotations:
   metallb.universe.tf/allow-shared-ip: ft_svcs
  labels:
   app: wordpress
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.0.3
  ports:
  - name: wordpress
    port: 5050
    targetPort: 5050
  selector:
    app: wordrpess